import os

API_KEY = os.getenv("SILICONFLOW_API_KEY", "")
API_BASE = "https://api.siliconflow.cn/v1"

EMBEDDING_MODEL = "Qwen/Qwen3-VL-Embedding-8B"
VISION_MODEL = "Qwen/Qwen3-VL-32B-Instruct"
RERANK_MODEL = "Qwen/Qwen3-VL-Reranker-8B"

TOP_N = 5
RETRY_COUNT = 4
RETRY_STATUSES = (429, 500, 502, 503, 504)
EMBEDDING_BATCH_SIZE = 64
EMBEDDING_TIMEOUT = 300.0  # a full batch can take >120s on a slow provider
RERANK_CANDIDATES = 20
PARSE_CONCURRENCY = 4

CHARACTER_WEIGHT = 3.0
USAGE_WEIGHT = 3.0
CONTENT_WEIGHT = 1.0
RRF_K = 60
